### ISSUE TITLE
can I make a pi with the bme680 hat act as a zigbee z-wave device ?

### ISSUE THREAD

**Issue by arkid** [pimoroni/bme680-python#21]
Don't panic, I'm not looking for detailed instructions, more a yes or no with a pointer to where to get started.

Thanks!

**Comment by Gadgetoid** [comment]
A quick Google suggests the answer is yes- it looks like there are both GPIO and USB add-ons for ZigBee/Z-Wave- however I have no experience with either. Since the BME680 uses only the i2c pins it’s unlikely there would be a conflict between it and a HAT or GPIO style add-on.
