### ISSUE TITLE
Broken link in readme?

### ISSUE THREAD

**Issue by christopherMills** [pimoroni/bme680-python#25]
https://learn.pimoroni.com/bme680
Shows a blank page.

**Comment by Gadgetoid** [comment]
Odd- https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-bme680-breakout should be showing up here rather than nothing at all.

I'll see if we can fix the learning portal and- if all else fails- update the link in the README.

**Comment by Gadgetoid** [comment]
Ah it was the wrong link- should be https://learn.pimoroni.com/bme680-breakout

Fixing! Thank you.

**Comment by christopherMills** [comment]
Fab, thank you so much!
