### ISSUE TITLE
Can this be used in micropython?

### ISSUE THREAD

**Issue by 17lwinn** [pimoroni/bme680-python#48]
Probably a stupid question, but would we be able to use this on a Raspberry Pi Pico W running micropython? I've seen a couple of issues on this but I just need a definite answer from someone, thanks.

**Comment by helgibbons** [comment]
Yep, it can - our [custom version of MicroPython](https://github.com/pimoroni/pimoroni-pico/releases) has drivers built in for this sensor.

Once you've [installed it](https://github.com/pimoroni/pimoroni-pico/blob/main/setting-up-micropython.md), there's a BME68x example [here](https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/examples/breakout_bme68x/bme68x_demo.py) and some documentation [here](https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/examples/breakout_bme68x).

**Comment by 17lwinn** [comment]
I'll give this a try, thanks!

**Comment by mamarais** [comment]
Thanks from me too!!! I have used the BME with a Raspberry Pi 3 to do long
term air quality monitoring, but   a Pico uses less power and can be placed
in more spots!!!

Rgds

Mario
